//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centapp.CartoonCommon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Centapp.CartoonCommon.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to favorites.
        /// </summary>
        internal static string addToFavText {
            get {
                return ResourceManager.GetString("addToFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.
        /// </summary>
        internal static string appHeader {
            get {
                return ResourceManager.GetString("appHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        internal static string backButtonText {
            get {
                return ResourceManager.GetString("backButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download episodes.
        /// </summary>
        internal static string backupEpisodesText {
            get {
                return ResourceManager.GetString("backupEpisodesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( Sorry, I can&apos;t find this video... Do you want to send an email to developers?.
        /// </summary>
        internal static string brokenLinkQuestion {
            get {
                return ResourceManager.GetString("brokenLinkQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in episode &apos;{0}&apos;
        ///Link: {1}
        ///.
        /// </summary>
        internal static string brokenLinkText {
            get {
                return ResourceManager.GetString("brokenLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to episodes!!!.
        /// </summary>
        internal static string ButtonEndText_DwnOk {
            get {
                return ResourceManager.GetString("ButtonEndText_DwnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report error.
        /// </summary>
        internal static string ButtonEndText_LinksKO {
            get {
                return ResourceManager.GetString("ButtonEndText_LinksKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start backup!.
        /// </summary>
        internal static string ButtonStartBackupEpisodesText {
            get {
                return ResourceManager.GetString("ButtonStartBackupEpisodesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy app.
        /// </summary>
        internal static string buyAppButton {
            get {
                return ResourceManager.GetString("buyAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes! .
        /// </summary>
        internal static string buyPage_buyApp {
            get {
                return ResourceManager.GetString("buyPage_buyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks....
        /// </summary>
        internal static string buyPage_noThanks {
            get {
                return ResourceManager.GetString("buyPage_noThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out this video!
        ///Title: {0}
        ///
        ///{1}.
        /// </summary>
        internal static string checkoutVideo {
            get {
                return ResourceManager.GetString("checkoutVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCLAIMER:
        ///
        ///This app is based on a public list of web videos links.
        ///Videos are hosted on YouTube servers and are not controlled by developers, that decline all responsibility for their content.
        ///If you want to request removal of a link, report broken/wrong link, contribute to expansion of the list, feel free to contact app authors.
        ///Names, trademarks, logos, text, graphics, images, sounds, videos, contained within this app belong to their respective owners.
        ///.
        /// </summary>
        internal static string disclaimerMessage {
            get {
                return ResourceManager.GetString("disclaimerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download episodes into your phone and watch them forever without internet connection?  :)
        ///.
        /// </summary>
        internal static string DownloadEpisodesQuestion {
            get {
                return ResourceManager.GetString("DownloadEpisodesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking videos urls . . .
        ///
        ///Please wait . . ..
        /// </summary>
        internal static string DownloaderPage_Infos_Stage_CheckingLinks {
            get {
                return ResourceManager.GetString("DownloaderPage_Infos_Stage_CheckingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( Oh no . . . 
        ///
        ///Wi-fi connection is no longer active...
        ///Please exit app, disable and enable wi-fi connection into phone settings and retry backup. 
        ///Downloaded episodes will be maintained.
        ///.
        /// </summary>
        internal static string DownloaderPage_Infos_Stage_DwnCompletedWithConnectionError {
            get {
                return ResourceManager.GetString("DownloaderPage_Infos_Stage_DwnCompletedWithConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( Oh no . . .
        ///
        ///Some episodes were not correctly downloaded: please retry backup procedure...
        ///Downloaded episodes will be maintained..
        /// </summary>
        internal static string DownloaderPage_Infos_Stage_DwnCompletedWithError {
            get {
                return ResourceManager.GetString("DownloaderPage_Infos_Stage_DwnCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done!!!
        ///
        ///All episodes are available into your phone: you&apos;ll no longer need internet connection!
        ///
        ///Enjoy them! :).
        /// </summary>
        internal static string DownloaderPage_Infos_Stage_DwnCompletedWithSuccess {
            get {
                return ResourceManager.GetString("DownloaderPage_Infos_Stage_DwnCompletedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in progress, please be patient :)
        ///
        ///Please do not exit this page, otherwise you will need to restart backup procedure . . ..
        /// </summary>
        internal static string DownloaderPage_Infos_Stage_DwnEpisodesInProgress {
            get {
                return ResourceManager.GetString("DownloaderPage_Infos_Stage_DwnEpisodesInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( Youtube removed some episodes...
        ///
        ///Please use button below to report problem to support: episodes will be fixed in 12-24h and you will receive an email when done..
        /// </summary>
        internal static string DownloaderPage_Infos_Stage_LinksCheckedWithErrors {
            get {
                return ResourceManager.GetString("DownloaderPage_Infos_Stage_LinksCheckedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! Here you can download all episodes from web! 
        ///
        ///Once done you can use app offline, all episodes will be available forever into your phone: internet connection will no longer required! 
        ///.
        /// </summary>
        internal static string DownloaderPage_Infos_Stage_Welcome {
            get {
                return ResourceManager.GetString("DownloaderPage_Infos_Stage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during Windows Phone Store connection! Please try again later or buy app from Store web page.
        /// </summary>
        internal static string error_buy {
            get {
                return ResourceManager.GetString("error_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during Windows Phone Store connection! Please try again later!.
        /// </summary>
        internal static string error_store {
            get {
                return ResourceManager.GetString("error_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this app :(
        ///Would you like to send an email to report it?.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem report.
        /// </summary>
        internal static string ExceptionMessageTitle {
            get {
                return ResourceManager.GetString("ExceptionMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        internal static string favoritesHeader {
            get {
                return ResourceManager.GetString("favoritesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but this feature is available only in offline mode, do you want to download episodes right now?.
        /// </summary>
        internal static string FavoritesOnlyInOfflineMode {
            get {
                return ResourceManager.GetString("FavoritesOnlyInOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorites episodes set.
        ///Tap and hold an episode to add it here.
        ///
        ///Tap and hold an episode in this list (if present) to remove it from favorites.
        /// </summary>
        internal static string favText {
            get {
                return ResourceManager.GetString("favText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feedback/request.
        /// </summary>
        internal static string feedbackText {
            get {
                return ResourceManager.GetString("feedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL version.
        /// </summary>
        internal static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        internal static string infoButtonText {
            get {
                return ResourceManager.GetString("infoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to repeat entire backup procedure, are you sure?.
        /// </summary>
        internal static string MessageAbortDownload {
            get {
                return ResourceManager.GetString("MessageAbortDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already done backup procedure, would you like to redo it?  .
        /// </summary>
        internal static string MessageAlreadyOffline {
            get {
                return ResourceManager.GetString("MessageAlreadyOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection not available!.
        /// </summary>
        internal static string noNetworkAvailable {
            get {
                return ResourceManager.GetString("noNetworkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( not enough space on device to save episodes... Required space: {0} Gb.
        /// </summary>
        internal static string notEnoughSpace {
            get {
                return ResourceManager.GetString("notEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but current episodes offline backup is not more valid: this version changed episodes catalogue and a new backup is neeeded!... a lot of new episodes were added!
        ///Do you want to backup right now?.
        /// </summary>
        internal static string OfflineRevertWarning {
            get {
                return ResourceManager.GetString("OfflineRevertWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other apps.
        /// </summary>
        internal static string otherAppsButton {
            get {
                return ResourceManager.GetString("otherAppsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected episode was not found into phone. 
        ///Maybe backup procedure hasn&apos;t completed correctly: please retry operation..
        /// </summary>
        internal static string possibleWrongBackup {
            get {
                return ResourceManager.GetString("possibleWrongBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate app!.
        /// </summary>
        internal static string rateAppButton {
            get {
                return ResourceManager.GetString("rateAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars :)
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        internal static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our app!
        ///
        ///Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        internal static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        internal static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying {0}?.
        /// </summary>
        internal static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        internal static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove from favorites.
        /// </summary>
        internal static string removeFromFavText {
            get {
                return ResourceManager.GetString("removeFromFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report broken link.
        /// </summary>
        internal static string reportError {
            get {
                return ResourceManager.GetString("reportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        internal static string season {
            get {
                return ResourceManager.GetString("season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server temporary unavailable :( 
        ///Please try again later... if problem persists please contact support.
        /// </summary>
        internal static string ServerTemporaryUnavailable {
            get {
                return ResourceManager.GetString("ServerTemporaryUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        internal static string shareText {
            get {
                return ResourceManager.GetString("shareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline episodes will occupy about {0}Gb of your phone memory. Continue?.
        /// </summary>
        internal static string SpaceRequiredWarn {
            get {
                return ResourceManager.GetString("SpaceRequiredWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to episode:.
        /// </summary>
        internal static string TextCurEpisodeTitleHeader {
            get {
                return ResourceManager.GetString("TextCurEpisodeTitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overall progress:.
        /// </summary>
        internal static string TextOverallProgressHeader {
            get {
                return ResourceManager.GetString("TextOverallProgressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIAL version.
        /// </summary>
        internal static string trial {
            get {
                return ResourceManager.GetString("trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but backup feature is not available into trial version...
        ///
        ///Do you want to buy full version?.
        /// </summary>
        internal static string trialMessageBackup {
            get {
                return ResourceManager.GetString("trialMessageBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you can watch only first five episodes into trial version...
        ///
        ///Do you want to buy full version?.
        /// </summary>
        internal static string trialMessageEpisodes {
            get {
                return ResourceManager.GetString("trialMessageEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( Sorry, something went wrong... Do you want to send an email to developers containing error details?.
        /// </summary>
        internal static string UserMessageDownloadKo {
            get {
                return ResourceManager.GetString("UserMessageDownloadKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wi-fi connection is required for download!.
        /// </summary>
        internal static string wifiRequired {
            get {
                return ResourceManager.GetString("wifiRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write us!.
        /// </summary>
        internal static string writeAnEmailButton {
            get {
                return ResourceManager.GetString("writeAnEmailButton", resourceCulture);
            }
        }
    }
}
